# Generated by Django 4.1.7 on 2023-02-23 15:27

from django.db import migrations
import calendar

all_ts = ['13:00', '13:40', '14:20', '14:40', '15:00', '15:40', '16:20', '17:00', '17:10', '18:00', '19:00/20:00']
lunch_ts = ['Lanche da Manha', 'Almoco', 'Lanche da Tarde', 'Jantar']


def insert_day_of_week(apps, schema_editor):
    DayOfWeek = apps.get_model('schedule', 'DayOfWeek')
    for d in calendar.day_name:
        dow = DayOfWeek(name=d)
        dow.save()


def insert_time_periods(apps, schema_editor):
    TimeSlot = apps.get_model('schedule', 'TimeSlot')
    for d in all_ts:
        TimeSlot(description=d, lunch_time_slot=False).save()
    for d in lunch_ts:
        TimeSlot(description=d, lunch_time_slot=True).save()


def insert_default_activities(apps, _):
    DayOfWeek = apps.get_model('schedule', 'DayOfWeek')
    TimeSlot = apps.get_model('schedule', 'TimeSlot')
    DailyActivity = apps.get_model('schedule', 'DailyActivity')
    initial_ts = [TimeSlot.objects.get(description=t) for t in all_ts]
    for dow in DayOfWeek.objects.all():
        DailyActivity(day_of_week=dow, time_slot=initial_ts[0], description='Ativ. Pedag.').save()
        DailyActivity(day_of_week=dow, time_slot=initial_ts[1], description='Ativ. Pedag.').save()
        DailyActivity(day_of_week=dow, time_slot=initial_ts[2], description='Recreio / Parque').save()
        DailyActivity(day_of_week=dow, time_slot=initial_ts[3], description='Lanche').save()
        DailyActivity(day_of_week=dow, time_slot=initial_ts[7], description='Saida 1').save()
        DailyActivity(day_of_week=dow, time_slot=initial_ts[8], description='Janta').save()
        DailyActivity(day_of_week=dow, time_slot=initial_ts[9], description='Saida 2').save()
        DailyActivity(day_of_week=dow, time_slot=initial_ts[10], description='Atividades').save()


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_day_of_week),
        migrations.RunPython(insert_time_periods),
        migrations.RunPython(insert_default_activities)
    ]
