# Generated by Django 4.1.7 on 2023-02-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20230223_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='entry_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.timeslot'),
        ),
    ]
