# Generated by Django 4.1.7 on 2023-03-19 17:41
import os
from django.db import migrations
from schedule.cardapio_parser import parse_file, labels


def insert_march_menu_entries(apps, _):
    BASE_DIR = os.path.dirname(os.path.dirname(__file__))
    print('base dir: ')
    print(BASE_DIR)
    TimeSlot = apps.get_model('schedule', 'TimeSlot')
    MenuEntry = apps.get_model('schedule', 'MenuEntry')
    for ts in TimeSlot.objects.filter(lunch_time_slot=True):
        ts.delete()
    time_slots = []
    for label in labels:
        ts = TimeSlot(lunch_time_slot=True, description=label)
        ts.save()
        time_slots.append(ts)
    for day, cafe, almoco, lanche, janta in parse_file(BASE_DIR + '/resources/cardapio-marco.txt', 3):
        MenuEntry(entry_date=day, entry_time=time_slots[0], entry=cafe).save()
        MenuEntry(entry_date=day, entry_time=time_slots[1], entry=almoco).save()
        MenuEntry(entry_date=day, entry_time=time_slots[2], entry=lanche).save()
        MenuEntry(entry_date=day, entry_time=time_slots[3], entry=janta).save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_menuentry_entry_time'),
    ]

    operations = [
        migrations.RunPython(insert_march_menu_entries),
    ]
